# Prometheus Configuration for KuroPanel V2
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "first_rules.yml"
#   - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # KuroPanel Application
  - job_name: 'kuropanel-app'
    static_configs:
      - targets: ['app:80']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # MySQL Database
  - job_name: 'kuropanel-mysql'
    static_configs:
      - targets: ['database:3306']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'kuropanel-redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if available)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
